In [1]:
import torch
cuda_ava = "Ture" if torch.cuda.is_available() else "False"
cuda_device = torch.cuda.get_device_name()
print("pytorch test:"+ cuda_ava +",device name:"+cuda_device)

pytorch test:Ture,device name:NVIDIA GeForce GTX 1080 Ti


/home/sever_162/anaconda3/envs/pytroch_bert/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from transformers import BertTokenizer, BertModel, BertForMaskedLM

In [3]:
BERT_PATH = "bert-base-cased"
tokenizer = BertTokenizer.from_pretrained(BERT_PATH)
print(tokenizer.tokenize('I have a good time, thank you.'))
bert = BertModel.from_pretrained(BERT_PATH)
print('load bert model over')

['I', 'have', 'a', 'good', 'time', ',', 'thank', 'you', '.']


Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


load bert model over


In [4]:
example_text = 'I will watch Memento tonight'
bert_input = tokenizer(example_text,padding='max_length', 
                       max_length = 12, 
                       truncation=True,
                       return_tensors="pt")
# ------- bert_input ------
print(bert_input['input_ids']) #tokens_tensor
print(bert_input['token_type_ids']) #segments_tensor
print(bert_input['attention_mask']) #masks_tensor

tensor([[  101,   146,  1209,  2824,  2508, 26173,  3568,   102,     0,     0,
             0,     0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])


In [5]:
example_text_2 = tokenizer.decode(bert_input.input_ids[0])
print(example_text_2)

[CLS] I will watch Memento tonight [SEP] [PAD] [PAD] [PAD] [PAD]


In [ ]:
class BERT(nn.Module):
    def __init__(self):
        super(BERT, self).__init__()
        self.bert_model = transformers.BertModel.from_pretrained("bert-base-uncased")
        self.dropout = nn.Dropout(0.1)
        #liner layer
        self.out = nn.linear(768,1)
        
    def forward(self,ids,mask,token_type_ids):
        _,output_bert = self.bert_model(ids,attention_mask = mask, token_type_ids= token_type_ids, return_dict=False)
        
        out= self.out(output_bert)
        
        return out

model = BERT()

loss_fn = nn.BCEWithLogitsLoss()

optimizer = optim.Adam(model.parameters(),lr=0.0001)